spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test
    username: sarumani
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rsocket:
    server:
      address: 118.67.132.220
      port: 8080
