spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test
    username: sarumani
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/sarumani/Documents/BackEnd/Jelog
  rsocket:
    server:
      address: 106.10.50.188
      port: 8080
